pipeline {
    agent any
    
    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }
        
        stage('Build Maven') {
            steps {
                // Execute Maven clean and install commands
                bat 'mvn -f comp367-webapp/pom.xml clean install'
            }
        }
        
        stage('Code Coverage') {
            steps {
                // Generate code coverage reports with Jacoco
                script {
                    bat 'mvn -f comp367-webapp/pom.xml jacoco:report'
                }
            }
        }
        
        stage('Docker Build') {
            steps {
                script {
                    // Change directory to where the Dockerfile is located
                    dir('comp367-webapp') {
                        // Build Docker image
                        bat 'docker build -t comp367-webapp .'
                    }
                }
            }
        }
        
        stage('Docker Login') {
            steps {
                script {
                    // Login to Docker Hub using username and password credentials
                    withCredentials([usernamePassword(credentialsId: 'dockerCredentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        // Use --password-stdin to avoid exposing the password in the command
                        // Escape the special character '$' in the password
                        def escapedPassword = "\$${env.DOCKER_PASSWORD}"
                        bat "echo $escapedPassword | docker login -u $DOCKER_USERNAME --password-stdin"
                    }
                }
            }
        }
        
        stage('Docker Push') {
            steps {
                script {
                    // Push Docker image to Docker Hub
                    bat 'docker push comp367-webapp:latest'
                }
            }
        }
    }
    
    post {
        success {
            echo 'Build successful!'
            // Additional post-build actions if needed
        }
        failure {
            echo 'Build failed!'
            // Additional post-build actions if needed
        }
    }
}
