pipeline {
    agent any

    triggers {
        githubPush()
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    def mvnHome = tool 'Maven3' // Updated Maven tool name
                    def mvnCMD = "${mvnHome}/bin/mvn"
                    
                    // Build the Maven project
                    sh "${mvnCMD} clean install"
                }
            }
        }
    }

    post {
        success {
            echo 'Build successful! '
        }
    }
}
